// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe89ByPLXNsr1GZ7KDAGcLLttIgSQxu-s',
    appId: '1:171004333124:web:66c764d22c8f6355320011',
    messagingSenderId: '171004333124',
    projectId: 'geofence-attendance-system',
    authDomain: 'geofence-attendance-system.firebaseapp.com',
    storageBucket: 'geofence-attendance-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQoWGWVAe3PtY5v1AuArmzx-91HlDutE',
    appId: '1:171004333124:android:0b290371892bd2f5320011',
    messagingSenderId: '171004333124',
    projectId: 'geofence-attendance-system',
    storageBucket: 'geofence-attendance-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8x9RCcMD47ze16fsFk-WRpOFHyND_Jg4',
    appId: '1:171004333124:ios:e940aeb4ace348c8320011',
    messagingSenderId: '171004333124',
    projectId: 'geofence-attendance-system',
    storageBucket: 'geofence-attendance-system.appspot.com',
    iosBundleId: 'com.example.geofenceAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8x9RCcMD47ze16fsFk-WRpOFHyND_Jg4',
    appId: '1:171004333124:ios:575de8e19eaf401e320011',
    messagingSenderId: '171004333124',
    projectId: 'geofence-attendance-system',
    storageBucket: 'geofence-attendance-system.appspot.com',
    iosBundleId: 'com.example.geofenceAttendanceSystem.RunnerTests',
  );
}
